### ISSUE TITLE
How to set report-fields ,use $scope 

### ISSUE THREAD

**Issue by klren0312** [dtagdev1/json-export-excel#16]
for example
`<button ng-json-export-excel data="datalist" report-fields="select" filename="'filename'" separator=',' class="btn-sm btn-primary">Export Excel</button>`

`$scope.select = "{id: 'ID Heder', DeviceName: 'DeviceName', udeviceId: 'udeviceId'}"`

**Comment by lifront** [comment]
Hi! is this problem solved？
