### ISSUE TITLE
default format of exported file is csv.

### ISSUE THREAD

**Issue by patelpalak8176** [dtagdev1/json-export-excel#4]
Hi,
Default format of exported file is csv.

I have modified file extension in FileSaver.js.

Its exporting now excel files with .xls format. But when I open it using Microsoft Excel it gives following warning everytime.

'The file format and extension do not match. file can be corrupted or unsafe.Unless you know this source don't open it. Do you want to open it anyway ?' : Yes : No

Is there any way to remove this warning ? 

Regards

**Comment by trantrunghieu0809** [comment]
You can use Microsoft Excel to open file csv.
