### ISSUE TITLE
Data is displayed in one column only

### ISSUE THREAD

**Issue by omarsafwany** [dtagdev1/json-export-excel#6]
Sometimes when I export the data to csv file, the data is displayed in the first column only. I have tried this on different platforms and it works on both and also displays incorrectly on both so I can't figure out the cause so far.

One thing I came across was the separator to be  `,` and I believe this is already done here:
`<button class="btn btn-sm btn-warning" ng-json-export-excel data="reports_index.models" report-fields="{'user_name': 'User', 'title': 'Title', 'department': 'Department', 'senior': 'Senior', 'assessment_name': 'Assessment Name', 'product_name': 'Product Name', 'submission_date': 'Submission Date', 'country': 'Country', 'score': 'Score'}", filename =" 'report' " class="css-class">Export</button>`

**Comment by trantrunghieu0809** [comment]
@omarsafwany thank you.
you can have configured wrong. You have extra comma.

config of you: `report-fields="{'user_name': 'User', 'title': 'Title', 'department': 'Department', 'senior': 'Senior', 'assessment_name': 'Assessment Name', 'product_name': 'Product Name', 'submission_date': 'Submission Date', 'country': 'Country', 'score': 'Score'}",`

config of me: `report-fields="{'user_name': 'User', 'title': 'Title', 'department': 'Department', 'senior': 'Senior', 'assessment_name': 'Assessment Name', 'product_name': 'Product Name', 'submission_date': 'Submission Date', 'country': 'Country', 'score': 'Score'}"`

**Comment by omarsafwany** [comment]
@dtagdev1  ok I removed the extra comma but still it's not the issue. As far as I understand, it is something related to the column delimiter. The current form appears in column separated by `;`. Anyway I can modify this delimiter?

**Comment by trantrunghieu0809** [comment]
You can use `separator` to modify  delimiter. EX:

`<button ng-json-export-excel data="dataList" report-fields="{'uesr.username': 'Heder 1', keyjson2: 'Header 2', keyjson3: 'Head 3'}" separator="," filename =" 'export-excel' " class="css-class"></button>`
